[package]
name = "hazard-sensor"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt-rtt = "0.4"
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "defmt"] }
embassy-nrf = { version = "0.11.0", features = ["defmt", "nrf52840", "time-driver-rtc1"] }
defmt = "1.1.1"
cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
static_cell = "2.1.1"
embedded-hal = { version = "1.0.0", features = ["defmt-03"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime"] }
embedded-hal-async = "1.0.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies.nrf-pac]
version = "0.4.0"
default-features = false
features = ["nrf52840"]
