[build]
target = "thumbv7em-none-eabi"

[target.thumbv7em-none-eabi]
# replace nRF82840_xxAA with your chip as listed in `probe-rs chip list`
# runner = "probe-rs run --chip nRF52840_xxAA"
runner = "powershell -ExecutionPolicy Bypass -File ./flash.ps1"
# runner = "C:/Program Files/Git/bin/bash.exe ./flash.sh"
rustflags = [
  "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "trace"
